name: mobilenet_w025_d025

model:
  type: mobilenet
  width_mult: 0.25
  depth_mult: 0.25
  num_classes: 8
  dropout: 0.1

audio:
  sample_rate: 16000
  n_mels: 16
  n_mfcc: 13
  win_length: 512
  hop_length: 256

train:
  batch_size: 1024
  epochs: 50
  lr: 0.001
  weight_decay: 0.0001
  early_stop_patience: 5
  seed: 123
